---
name: build release

on:
 pull_request:
    types: [opened, synchronize, closed]
    branches:
      - master

env:
  ENVIRONMENT: balena-cloud.com
  BLOCK: balenablocks/ca-private

jobs:
  build-release:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        arch: [amd64]

    steps:
      - uses: actions/checkout@v3

      - name: push draft or finalise release
        uses: balena-io/balena-ci@master
        with:
          balena_token: ${{ secrets.BALENA_API_KEY }}
          cache: false
          fleet: ${{ env.BLOCK }}-${{ matrix.arch }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          versionbot: true
